'use client'

import { useEffect, useState } from "react"
import { nudgesApi, Nudge } from "@/lib/api"

export default function NudgesPage() {
    const [nudges, setNudges] = useState<Nudge[]>([])
    const [isLoading, setIsLoading] = useState(true)

    useEffect(() => {
        const fetchNudges = async () => {
            try {
                const data = await nudgesApi.list()
                setNudges(data)
            } catch (error) {
                console.error("Failed to fetch nudges:", error)
            } finally {
                setIsLoading(false)
            }
        }
        fetchNudges()
    }, [])

    const handleRate = async (nudgeId: string, rating: number) => {
        // Optimistic UI update: instantly update the UI so it feels snappy
        setNudges(prev => 
            prev.map(n => n.id === nudgeId ? { ...n, rating } : n)
        )
        try {
            await nudgesApi.rate(nudgeId, rating)
        } catch (error) {
            console.error("Failed to rate nudge:", error)
            // Revert on failure could go here
        }
    }

    if (isLoading) {
        return (
            <div className="flex min-h-screen items-center justify-center bg-[#0e0d0b]">
                <div className="h-6 w-6 animate-spin rounded-full border-2 border-[#1a1815] border-t-[#c8a96e]"></div>
            </div>
        )
    }

    return (
        <div className="min-h-screen bg-[#0e0d0b] px-6 py-12 text-[#e8e4dc] font-sans">
            <div className="mx-auto max-w-2xl">
                <header className="mb-10 border-b border-[#1a1815] pb-6">
                    <h1 className="font-['Lora'] text-3xl text-[#c8bfb0]">Your Insights & Nudges</h1>
                    <p className="mt-2 text-[14px] font-light text-[#6b6357]">
                        Personalized interventions generated by your emotional landscape.
                    </p>
                </header>

                {nudges.length === 0 ? (
                    <div className="flex h-40 flex-col items-center justify-center rounded-xl border border-[#1a1815] bg-[#0c0b09]">
                        <p className="text-[14px] text-[#4a4438] font-light">No nudges generated yet.</p>
                        <p className="text-[12px] text-[#4a4438] mt-1">Keep journaling to receive insights.</p>
                    </div>
                ) : (
                    <div className="space-y-4">
                        {nudges.map((nudge) => (
                            <div 
                                key={nudge.id} 
                                className="group relative overflow-hidden rounded-xl border border-[#1a1815] bg-[#0c0b09] p-6 transition-colors hover:border-[#2a2720]"
                            >
                                {/* Subtle gold accent edge if unrated */}
                                {nudge.rating === null && (
                                    <div className="absolute left-0 top-0 h-full w-[2px] bg-[#c8a96e]/50"></div>
                                )}
                                
                                <div className="mb-4 flex items-center justify-between">
                                    <span className="rounded-md bg-[#141210] px-2 py-1 text-[11px] font-medium uppercase tracking-wider text-[#c8a96e]">
                                        {nudge.nudge_type}
                                    </span>
                                    <span className="text-[11px] text-[#4a4438]">
                                        {new Date(nudge.created_at).toLocaleDateString("en-GB", {
                                            day: "numeric", month: "short"
                                        })}
                                    </span>
                                </div>
                                
                                <p className="mb-6 font-['Lora'] text-[16px] leading-relaxed text-[#e8e4dc]">
                                    {nudge.content}
                                </p>

                                <div className="flex items-center gap-3 border-t border-[#1a1815] pt-4">
                                    <span className="text-[12px] text-[#6b6357]">Was this helpful?</span>
                                    <button 
                                        onClick={() => handleRate(nudge.id, 1)}
                                        className={`flex h-8 w-8 items-center justify-center rounded-full transition-all ${
                                            nudge.rating === 1 
                                            ? "bg-[#c8a96e] text-[#0e0d0b]" 
                                            : "border border-[#2a2720] text-[#6b6357] hover:border-[#c8a96e] hover:text-[#c8a96e]"
                                        }`}
                                    >
                                        👍
                                    </button>
                                    <button 
                                        onClick={() => handleRate(nudge.id, -1)}
                                        className={`flex h-8 w-8 items-center justify-center rounded-full transition-all ${
                                            nudge.rating === -1 
                                            ? "bg-[#8a2a2a] text-[#e8e4dc]" 
                                            : "border border-[#2a2720] text-[#6b6357] hover:border-[#8a2a2a] hover:text-[#8a2a2a]"
                                        }`}
                                    >
                                        👎
                                    </button>
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </div>
        </div>
    )
}