import os
from fpdf import FPDF
from datetime import datetime

class MoodReportPDF(FPDF):
    def __init__(self, start_date: str, end_date: str):
        super().__init__()
        self.start_date = start_date
        self.end_date = end_date

    def header(self):
        """Automatically called at the top of every page"""
        # Arial bold 15
        self.set_font("helvetica", "B", 18)
        # Title
        self.set_text_color(79, 70, 229) # Indigo color (Tailwind Indigo-600)
        self.cell(0, 10, "MoodMap Weekly Report", align="C", new_x="LMARGIN", new_y="NEXT")
        
        # Subtitle (Date Range)
        self.set_font("helvetica", "I", 12)
        self.set_text_color(107, 114, 128) # Gray color
        self.cell(0, 10, f"{self.start_date} to {self.end_date}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(10) # Add a line break

    def footer(self):
        """Automatically called at the bottom of every page."""
        # Go to 1.5 cm from bottom
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(156, 163, 175)
        # Page number
        self.cell(0, 10, f"Page {self.page_no()}", align="C")
        
        # Disclaimer
        self.set_y(-10)
        self.cell(0, 10, "Disclaimer: This report is generated by AI and is not a clinical diagnosis.", align="C")


def generate_weekly_report(
    file_path: str,
    start_date: str,
    end_date: str,
    trend_summary: str,
    themes: list,
    nudge_log: list
):
    """
    Takes the compiled data and draws the actual PDF document
    """
    pdf = MoodReportPDF(start_date, end_date)
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # --- SECTION 1: Mood Summary ---
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(31, 41, 55)
    pdf.cell(0, 10, "1. Weekly Mood Summary", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 12)
    pdf.multi_cell(0, 8, trend_summary)
    pdf.ln(5)

    # --- SECTION 2: Top Journal Themes (GenSim LDA Output) ---
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "2. Top Themes Discussed", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_font("helvetica", "", 12)
    if not themes:
        pdf.multi_cell(0, 8, "Not enough journal text this week to extract themes.")
    else:
        for i, theme in enumerate(themes, 1):
            pdf.cell(0, 8, f"{i}. {theme}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # --- SECTION 3: Intervention & Nudge History ---
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "3. Proactive Interventions", new_x="LMARGIN", new_y="NEXT")
    
    if not nudge_log:
        pdf.set_font("helvetica", "I", 12)
        pdf.cell(0, 10, "No proactive nudges were triggered this week.", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.set_font("helvetica", "B", 10)
        # Table Header
        pdf.cell(40, 10, "Date", border=1)
        pdf.cell(40, 10, "Type", border=1)
        pdf.cell(80, 10, "Trigger Reason", border=1)
        pdf.cell(30, 10, "User Rating", border=1, new_x="LMARGIN", new_y="NEXT")
        
        pdf.set_font("helvetica", "", 10)
        for nudge in nudge_log:
            # Map rating to text
            rating_str = "Helpful" if nudge['rating'] == 1 else "Not Helpful" if nudge['rating'] == -1 else "Neutral"
            
            pdf.cell(40, 10, nudge['date'], border=1)
            pdf.cell(40, 10, nudge['type'].capitalize(), border=1)
            pdf.cell(80, 10, nudge['reason'][:40] + "...", border=1) # Truncate long reasons
            pdf.cell(30, 10, rating_str, border=1, new_x="LMARGIN", new_y="NEXT")

    # Save the PDF to the hard drive temporarily
    pdf.output(file_path)
    return file_path