"""add audio_key mood_tags status to journal_entries

Revision ID: 79054a8d065c
Revises: dbd7b70c89d7
Create Date: 2026-04-10 20:18:17.479909

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79054a8d065c'
down_revision: Union[str, Sequence[str], None] = 'dbd7b70c89d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal_entries', sa.Column('audio_key', sa.String(), nullable=True))
    op.add_column('journal_entries', sa.Column('mood_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('journal_entries', sa.Column('status', sa.Enum('PENDING', 'QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', name='analysis_status'), nullable=True))
    op.drop_column('journal_entries', 'audio_url')
    op.drop_index(op.f('mood_scores_time_idx'), table_name='mood_scores')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('mood_scores_time_idx'), 'mood_scores', [sa.literal_column('time DESC')], unique=False)
    op.add_column('journal_entries', sa.Column('audio_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('journal_entries', 'status')
    op.drop_column('journal_entries', 'mood_tags')
    op.drop_column('journal_entries', 'audio_key')
    # ### end Alembic commands ###
